CREATE DATABASE CADASTRO;
USE CADASTRO; 

CREATE TABLE usuario(
id INT(11) NOT NULL AUTO_INCREMENT,
nome VARCHAR(50) NULL DEFAULT NULL,
senha VARCHAR(50) NULL DEFAULT NULL, 
PRIMARY KEY (id)); 

SELECT * FROM usuario